### PR TITLE
Cats

### PR DESCRIPTION
**Pull request by Bazzaware**
Code added for the Cats class with tests for Eat and Walk methods.

### CODE REVIEW

**Review by NicoHarrison1 — APPROVED** [review]
looks good bro

**Review by NicoHarrison1 — APPROVED** [review]
i approve

**Comment by Bazzaware** [comment]
Did you get a pop up about this ??
@NicoHarrison1

**Review by NicoHarrison1 — APPROVED** [review]
LET ME APPEOVE IT DAMMIT

**Pull request merged**
